### PR TITLE
Add pathTo in DragApply function for "change" event 

### PR DESCRIPTION
**Pull request by iceflash**
Add pathTo in DragApply function for "change" event + fix 'g is undefined' check 'elCopy'

### CODE REVIEW

**Comment by rhwilr** [comment]
@iceflash Can you quickly describe why you need the `pathTo` in the change event and what this allows you to do? 
Since this would be a breaking change, we would have to release version 3.0 for this.

**Comment by iceflash** [comment]
@rhwilr Thanks!) I use it to determine the position in the final array and not to re-search, since I can have a rather deep level of nesting of elements. So it very useful

**Comment by rhwilr** [comment]
That makes sense. But I think we should try not to break the API when ever possible. 

Instead of changing the data to an object, we could pass a second parameter in the event that is an `arguments` object. `$emit` does allow for [multiple arguments](https://vuejs.org/v2/api/#vm-emit).

I'm thinking something like this:
```js
this.$emit('change', this.dragItem, { pathTo: this.pathTo })
```

**Comment by iceflash** [comment]
@rhwilr i agree) i will make changes

**Comment by rhwilr** [comment]
:+1: Thanks @iceflash, great work!

**Comment by iceflash** [comment]
You are welcome @rhwilr, thanks for your component!:+1:

**Pull request merged**
