### PR TITLE
Use slot-proxy pattern instead of custom _b

### PR DESCRIPTION
**Pull request by pbastowski**
I noticed your disclaimer, warning against using this package in production due to the use of the custom `_b` function polyfill. This PR will allow you to remove that disclaimer.

I have refactored the code in three places, to pass on any and all scoped slots using the currently available Vue version, without hacks. I built it locally inside my node_modules and ran a test to verify it still works the same as your original. For me it does.

### CODE REVIEW

**Comment by pbastowski** [comment]
Ahh, I accidentally pushed the dist folder just now. Sorry. I was going to only update my fork's master dist folder to allow me to temporarily use the package directly from git.
But, I guess you will rebuild anyway, so, things should be ok in the end.

**Comment by rhwilr** [comment]
@pbastowski Thanks! :+1:  
I will take a closer look at this in the next few days.

**Comment by rhwilr** [comment]
:tada:  Thanks @pbastowski! Nice work.

**Comment by pbastowski** [comment]
You are welcome

**Pull request merged**
